<?php echo $this->flashSession->output(); 
 
 $username='';
 $password='';
 $rememberMe='';

 if($this->cookies->has("username") && $this->cookies->has("password") )
 {
     $username=$this->cookies->get("username");
     $password=$this->cookies->get("password");
     $rememberMe='checked';
 }
?>
<link rel="stylesheet" type="text/css" href="public/css/background.css">
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<script src="http://mymaplist.com/js/vendor/TweenLite.min.js"></script>
<!-- This is a very simple parallax effect achieved by simple CSS 3 multiple backgrounds, made by http://twitter.com/msurguy -->

 <form action="" method="post">
 </br> </br> </br> </br> </br> </br>
 <div class="container">
   <div class="row vertical-offset-100">
       <div class="col-md-4 col-md-offset-4">
           <div class="panel panel-default">
                 <div class="panel-heading">
                   <h3 class="panel-title">Please sign in</h3>
                </div>
                 <div class="panel-body">
                   <form accept-charset="UTF-8" role="form">
                   <fieldset>
                         <div class="form-group">
                           <input type="email" name="email" class="form-control" id="email" placeholder="Enter email" value="<?php if(isset($username))echo $username; ?>" required>
                       </div>
                       <div class="form-group">
                           <input type="password" name="password" class="form-control" id="password" placeholder="Password" value="<?php if(isset($password))echo $password; ?>" required>
                       </div>
                       <div class="checkbox">
                           <label>
                               <input type="checkbox" name="rememberMe" class="form-check-input" id="rememberMe" value="1" <?php echo $rememberMe;?>> Remember Me
                           </label>
                       </div>
                       <button type="submit" class="btn btn-primary">Submit</button>
                       <a href="<?php echo $this->url->getBaseUri(); ?>" class="btn btn-warning">Back</a>
                   </fieldset>
                     </form>
               </div>
           </div>
       </div>
   </div>
</div>
  
 </form>

  
